### ISSUE TITLE
Decompiler does not work in macOS 10.15 due to "dyld: Symbol not found" error

### ISSUE THREAD

**Issue by gammalogic** [NationalSecurityAgency/ghidra#7194]
**Describe the bug**
The decompiler does not work because of a missing C++ symbol when using Ghidra 11.1.2 on macOS 10.15 (Catalina). The error message I get at the command line is

> dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
> Referenced from: /Users/mac/ghidra_11.1.2_PUBLIC/Ghidra/Features/Decompiler/os/mac_x86_64/./decompile (which was built for Mac OS X 14.0)
> Expected in: /usr/lib/libc++.1.dylib
> 
> zsh: abort

and within the application is

>   Decompiler: Unable to initialize the DecompilerInterface: Decompiler process failed to launch (see log for details)

and in the project log is

> 2024-11-11 13:13:47 ERROR (DecompileProcess) Failed to launch Decompiler process: Decompiler executable may not be compatible with your system and may need to be rebuilt.
> (see InstallationGuide.html, 'Building Native Components').
> 
> dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
>   Referenced from: /Users/mac/ghidra_11.1.2_PUBLIC/Ghidra/Features/Decompiler/os/mac_x86_64/decompile 
> (which was built for Mac OS X 14.0)
>   Expected in: /usr/lib/libc++.1.dylib

**To Reproduce**
Run the following command at the command line

`/Users/mac/ghidra_11.1.2_PUBLIC/Ghidra/Features/Decompiler/os/mac_x86_64/decompile`

**Expected behavior**
The decompiler application should run without generating any errors.

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Java Version: Eclipse Temurin 21
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro (ghidra_11.1.2_PUBLIC_20240709.zip)

**Additional context**
Although my version of macOS is not recent, it appears to meet the minimum system requirements. I have not attempted to build any native components yet as mentioned in the documents.

Thank you in advance for any help.

**Comment by ghidra1** [comment]
Our natives for Mac are currently built with Mac OS 15.x Sequoia.  I recommend you rebuild your natives using the `buildNatives` script.  You will need gradle installed.  Please see the Installation Guide for more info.

**Comment by gammalogic** [comment]
Thank you. I've followed the instructions in the installation guide and the decompiler is now working.

**Comment by ghidra1** [comment]
Glad to hear it.
