### ISSUE TITLE
NoClassDefFoundError writing simple GhidraScript when importing decompiler class

### ISSUE THREAD

**Issue by good5068** [NationalSecurityAgency/ghidra#2935]
when i write a simple ghidra script that i want to do some searching in decompiler, It report NoClassDefFoundError.
Here is my simplified version:
```
    import ghidra.app.decompiler.component.ClangFieldElement;
    import ghidra.app.script.GhidraScript;
    public class testSimple_zzz extends GhidraScript{
    
	    @Override
	    protected void run() throws Exception {
		    // TODO Auto-generated method stub
		    ClangFieldElement e=new ClangFieldElement(null,null, 1);
	    }
	    
    }
```

There is no problem in my eclipse project,but wheren i run , it produced NoClassDefFoundError 👍 

```
    _ERROR Task Error: testSimple_zzz.java - Uncaught Exception: java.lang.NoClassDefFoundError: ghidra/app/decompiler/component/ClangFieldElement (RunScriptTask) java.lang.NoClassDefFoundError: ghidra/app/decompiler/component/ClangFieldElement
	    at testSimple_zzz.run(testSimple_zzz.java:8)
	    at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	    at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	    at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	    at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	    at ghidra.util.task.Task.monitoredRun(Task.java:124)
	    at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	    at java.base/java.lang.Thread.run(Thread.java:834)_
```

**Comment by jpleasu** [comment]
I can't recreate on Linux, JDK11, master or 9.2.2.  Can you share your environment details 👍🏻 ?

**Comment by good5068** [comment]
> I can't recreate on Linux, JDK11, master or 9.2.2. Can you share your environment details 👍🏻 ?

My env is:
os：windows 10 x64
jdk 11
ghidra 9.2.2

**Comment by jpleasu** [comment]
Ok, I'm set up - but I still can't recreate.  I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.

In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.

Where is your Ghidra installed?

**Comment by good5068** [comment]
> Ok, I'm set up - but I still can't recreate. I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.
> 
> In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.
> 
> Where is your Ghidra installed?

my ghidra is in:
D:\soft\ghidra_9.2.2_PUBLIC
my script file is in:
D:\ghidra922

I recreate this many times.

**Comment by good5068** [comment]
> Ok, I'm set up - but I still can't recreate. I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.
> 
> In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.
> 
> Where is your Ghidra installed?

my decompiler.jar is in:
D:\soft\ghidra_9.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar

**Comment by jpleasu** [comment]
> I recreate this many times.
I would hope so if you're going through the trouble of creating an issue :-)

Since I can't recreate your issue, I'll start guessing until someone with a better idea pops up.

Do any of your scripts implement classes in the package `ghidra.app.decompiler.component`?

**Comment by good5068** [comment]
> Ok, I'm set up - but I still can't recreate. I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.
> 
> In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.
> 
> Where is your Ghidra installed?

en! very sorry.  I create a new virtual machine and i didn't find this problem again,
I think it's because of my env also exists 9.1.2, I will report a detailed result later

**Comment by good5068** [comment]
> > Ok, I'm set up - but I still can't recreate. I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.
> > In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.
> > Where is your Ghidra installed?
> 
> en! very sorry. I create a new virtual machine and i didn't find this problem again,
> I think it's because of my env also exists 9.1.2, I will report a detailed result later

I reproduced it:
So, when I only launch ghidra without eclipse, the code works.
But when I installed eclipse and using eclipse to debug as->ghidra, the problem appears.
After then, I only launch ghidra , problem didn't dispear.

**Comment by good5068** [comment]
> > Ok, I'm set up - but I still can't recreate. I tired from `ghidraRun.bat` and from the Ghidra launch configuration in eclipse.
> > In my install, `ClangFieldElement` is found in `C:\ghidra_9.2.2_PUBLIC\Ghidra\Features\Decompiler\lib\Decompiler.jar`.
> > Where is your Ghidra installed?
> 
> en! very sorry. I create a new virtual machine and i didn't find this problem again,
> I think it's because of my env also exists 9.1.2, I will report a detailed result later

I think It's because my project have more classes, only testsimple_zzz.java didn't produce that problem.

**Comment by jpleasu** [comment]
Are you using the latest GhidraDev eclipse plugin?

You could try creating a new Ghidra launch configuration:
![image](https://user-images.githubusercontent.com/1778531/114723616-cb3cf100-9d08-11eb-8ddb-7782836b8a26.png)

**Comment by good5068** [comment]
The problem is solved,but I post the reason here:
I create a class that package with in ghidra decompiler's class path:
`package ghidra.app.decompiler.component;
....
/**
 * 
 *
 * Control the GUI layout for displaying tokenized C code
 */
public class MyDecompilerSearch2 implements LayoutModel, LayoutModelListener {

	private final ClangFieldElement EMPTY_LINE_NUMBER_SPACER;
.....
public MyDecompilerSearch2(DecompileOptions opt, DecompilerPanel decompilerPanel,
			FontMetrics met, HighlightFactory hlFactory,Program p) {
		options = opt;
		this.decompilerPanel = decompilerPanel;
		syntax_color = new Color[9];
		programself=p;
		metrics = met;
		this.hlFactory = hlFactory;
		EMPTY_LINE_NUMBER_SPACER = createEmptyLineNumberSpacer();
		listeners = new ArrayList<>();
		buildLayouts(null, null, null, false);
	}
`
and when I use this class in my script file ,this error occor:
`java.lang.NoClassDefFoundError: ghidra/app/decompiler/component/ClangFieldElement`

I solved this problem by not package this class to ghidra's inner path：
just remove this line 👍 
package ghidra.app.decompiler.component
will work.

because the script works in my 9.1.2 , and I really reproduced it many times.
Thanks for your help, It's really a nice job!!

**Comment by jpleasu** [comment]
Ok, I'm glad you're up and running!  Closing the ticket.
