### ISSUE TITLE
Build from source failure at commit 1aa7b089

### ISSUE THREAD

**Issue by thixotropist** [NationalSecurityAgency/ghidra#8342]
**Describe the bug**
Building Ghidra from source fails after commit 1aa7b089 with multiple failures to find symbol `ghidra.framework.data.NullFolderDomainObject`.  Bisection shows a proper build at the previous commit.

**To Reproduce**
* check out 1aa7b089 or its merge to master at 53552616
* gradle -I gradle/support/fetchDependencies.gradle
* gradle buildGhidra

```text
Task :Project:compileJava FAILED
/home/gary/projects/github/ghidra/Ghidra/Framework/Project/src/main/java/ghidra/framework/protocol/ghidra/GhidraURLQuery.java:26: error: cannot find symbol
import ghidra.framework.data.NullFolderDomainObject;
                            ^
  symbol:   class NullFolderDomainObject
  location: package ghidra.framework.data
```

```text
Java: 22
Gradle: 8.8
Python3 command: [python3.13] (3.13, /usr/bin/python3.13)
Python3 pip version: 24.3.1
OS: Linux
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64
```

**Comment by astrelsky** [comment]
This should be fixed now, I just pulled in the current changes and built without a problem.

**Comment by dev747368** [comment]
Also, try doing a clean.  I had this exact error and I needed a clean to fix it.

**Comment by ryanmkurtz** [comment]
Same issue. `gradle clean` fixed it.

**Comment by thixotropist** [comment]
Thanks!  Looking good now.  For the future, is there anything to add to `DevGuide.md` to show when `gradle clean` might be necessary?  For instance when doing a series of builds under `git bisect`?

**Comment by ryanmkurtz** [comment]
This was a pretty rare scenario.  I can't recall ever actually having to do it before.
