### ISSUE TITLE
PyDev 9.x debugging not working

### ISSUE THREAD

**Issue by dummys** [NationalSecurityAgency/ghidra#3378]
Hi, 

I'm trying to use eclipse with GhidraDev plugin to debug a ghidra script in python.
The problem is that when selecting Debug- > Ghidra, it opens successfully ghidra, then I run my script but then there is no more actions. I can't use resume, suspend, step line etc. Is there some bug with latest version of Ghidra ? My version is 10.0.0.2

Here is the logs I found inside eclipse:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/eclipse/plugins/org.python.pydev.core_9.0.1.202108191530/pysrc/pydevd.py", line 24, in <module>
    from _pydevd_bundle import pydevd_constants
  File "/opt/eclipse/plugins/org.python.pydev.core_9.0.1.202108191530/pysrc/_pydevd_bundle/pydevd_constants.py", line 365, in <module>
    from _pydev_imps._pydev_saved_modules import thread, threading
  File "/opt/eclipse/plugins/org.python.pydev.core_9.0.1.202108191530/pysrc/_pydev_imps/_pydev_saved_modules.py", line 97, in <module>
    import thread;    verify_shadowed.check(thread, ['start_new_thread', 'start_new', 'allocate_lock'])
  File "/opt/eclipse/plugins/org.python.pydev.core_9.0.1.202108191530/pysrc/_pydev_imps/_pydev_saved_modules.py", line 73, in check
    msg = self._generate_shadowed_import_message([module.__file__])
AttributeError: type object 'org.python.modules.thread.thread' has no attribute '__file__'
go_func.py> Finished!

```

**Comment by dummys** [comment]
yes ok thanks, but I think there is another problem is you read the log i wrote. Did you have an idea ? something wrong with pydev ?

**Comment by ryanmkurtz** [comment]
Can you try using PyDev 8.3.0?  I see the 9.x versions recently came out and I haven't tried them yet....there might be a problem with them that we'll need to address.

**Comment by dummys** [comment]
problem is that I don't know if it is possible to downgrade. It's written pydev 8.3.0 inside the eclipse marketplace ...

**Comment by ryanmkurtz** [comment]
Hmm, it looks like they didn't update the text in the Eclipse Marketplace...they are giving us 9.0.1 with it, despite it saying 8.3.0 in the description.  You can uninstall your current PyDev by doing Help -> About Eclipse IDE -> Installation Details -> Select PyDev -> Uninstall.

PyDev 8.3.0 can be manually downloaded [here](https://sourceforge.net/projects/pydev/files/pydev/PyDev%208.3.0/).
Instructions for installing the .zip file can be found [here](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.0.2_build/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/GhidraDev_README.html#PyDevInstall).

**Comment by dummys** [comment]
ok I will test with it

**Comment by ryanmkurtz** [comment]
I am also having issues with PyDev 9, so we can use this issue to track the fix.  Once you confirm things are working with PyDev 8.3, we should rename this issue to indicate that it's a PyDev 9 compatibility issue.

**Comment by dummys** [comment]
latest version of eclipse do not work with your version, see screen
![2021-08-31_09-24](https://user-images.githubusercontent.com/1941445/131460781-e148ab37-e486-479f-9075-59e5dcfef22d.png)

**Comment by ryanmkurtz** [comment]
The latest version of Eclipse is 2021-06.  What JDK version are you using?

**Comment by dummys** [comment]
oups will update it tomorrow then. Im at openJDK-16

**Comment by zZeck** [comment]
The original post in this issue is a pydev 9 problem. I get the same traceback.

Here is what I have found so far.

The problem originates in pysrc/_pydev_imps/_pydev_saved_modules.py which [very recently](https://github.com/fabioz/Pydev/commits/5d11ff48cd9eee3db08b8c442ddc5315f8cc68ed/plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py) changed significantly. Problem happens when pydev is [checking for shadowed imports for the thread module](https://github.com/fabioz/Pydev/blob/5d11ff48cd9eee3db08b8c442ddc5315f8cc68ed/plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py#L97). The [check](https://github.com/fabioz/Pydev/blob/5d11ff48cd9eee3db08b8c442ddc5315f8cc68ed/plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py) method is slightly before this in the file. The line that [causes the crash](https://github.com/fabioz/Pydev/blob/5d11ff48cd9eee3db08b8c442ddc5315f8cc68ed/plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py#L73) is in the except handler for the check function, which indicates the main part of check isn't finding one of the attributes it expects on the thread module I believe. Those are ['start_new_thread', 'start_new', 'allocate_lock'].

This seems strange because the jython builtin thread module looks like it should have [those functions](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/indexer/Builtins.java#L2177). I can see why it wouldn't have \_\_file\_\_ attribute since it's a built in, but I don't think execution should even be in that except block.

I'll try to look around some more later.

**Comment by zZeck** [comment]
In ghidra, thread.start_new does not exist. Tested in the python console.

import thread
thread.start_new_thread
<java function start_new_thread 0x2>
thread.allocate_lock
<java function allocate_lock 0x3>
thread.start_new
Traceback (most recent call last):
  File "python", line 1, in <module>
AttributeError: type object 'org.python.modules.thread.thread' has no attribute 'start_new'

**Comment by zZeck** [comment]
start_new seems to be an [old name](https://github.com/python/cpython/blob/main/Modules/_threadmodule.c#L1175) for start_new_thread

I the [jython tests](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/lib-python/2.7/dummy_thread.py#L15) that skips obsolete methods in the thread module.

There is also a note [here](https://www.jython.org/jython-old-sites/archive/21/docs/differences.html) indicating the obsolete aliases in thread module are not supported.

> thread module
CPython's thread modules defines some aliases that Jython's doesn't. These aliases are considered obsolete and won't be supported by Jython.

I think the solution is some change over in the pydev. There is a file where they [monkey patch start_new](https://github.com/fabioz/Pydev/blob/cd7bb8c3df5cd3231c2bb4d4954e0314a920afb0/plugins/org.python.pydev.core/pysrc/_pydev_bundle/pydev_monkey.py#L1152) and even mentions of what look like a jython work arounds for [something else](https://github.com/fabioz/Pydev/blob/cd7bb8c3df5cd3231c2bb4d4954e0314a920afb0/plugins/org.python.pydev.core/pysrc/_pydev_bundle/pydev_monkey.py#L1101) in the same file.

**Comment by zZeck** [comment]
I'm going to have to do more investigation.

There are still problems using pydev wtih ghidra jython beyond the start_new. If you fix that, the next error is this

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\X\\.p2\pool\plugins\org.python.pydev.core_9.0.1.202108191530\pysrc\pydevd.py", line 24, in <module>
>     from _pydevd_bundle import pydevd_constants
>   File "C:\Users\Zechariah\\.p2\pool\plugins\org.python.pydev.core_9.0.1.202108191530\pysrc\_pydevd_bundle\pydevd_constants.py", line 365, in <module>
>     from _pydev_imps._pydev_saved_modules import thread, threading
>   File "C:\Users\X\\.p2\pool\plugins\org.python.pydev.core_9.0.1.202108191530\pysrc\_pydev_imps\_pydev_saved_modules.py", line 81, in <module>
>     import threading;    verify_shadowed.check(threading, ['Thread', 'settrace', 'setprofile', 'Lock', 'RLock', 'current_thread'])
>   File "C:\Users\X\Programs\ghidra_10.0_PUBLIC\Ghidra\Features\Python\data\jython-2.7.2\Lib\threading.py", line 88, in <module>
>     ThreadStates = {
> AttributeError: type object 'java.lang.Thread' has no attribute 'State'

Maybe related to this jython issue with loading imports in multiple threads?

https://bugs.jython.org/issue2642

In the ghidra python console, java.lang.Thread.State also doesn't exist.

> from java.lang import Thread
> Thread
> <type 'java.lang.Thread'>
> Thread.State
> Traceback (most recent call last):
>   File "python", line 1, in <module>
> AttributeError: type object 'java.lang.Thread' has no attribute 'State'

Strangely, it does show up in the dir listing. I know it's possible for a property to exist on an object and have its getter throw an AttributeError. Dunno what is going on.
print(dir(Thread))
['MAX_PRIORITY', 'MIN_PRIORITY', 'NORM_PRIORITY', __'State'__,  ....]


Any ideas?

**Comment by ryanmkurtz** [comment]
Thanks for looking into this @zZeck.  I haven't had a chance to starting looking into this in detail but I appreciate your efforts.

**Comment by zZeck** [comment]
What ever issue I was having with Thread.State must be unrelated. After relaunching ghidra today to look around more, it isn't happening.  Removing the 'start_new' check from pydev makes 9.0.1 work fine in ghidra.

**Comment by ryanmkurtz** [comment]
I was able to reproduce all the same errors you are seeing.  I also did a test independent of Ghidra, with a standalone PyDev 9.1.0  project pointing to a full installation of jython 2.7.2, and got a similar error when trying to debug:
```
  File "/home/ryan/.eclipse/org.eclipse.platform_4.21.0_1473617060_linux_gtk_x86_64/plugins/org.python.pydev.core_9.1.0.202110031145/pysrc/_pydevd_bundle/pydevd_constants.py", line 365, in <module>
    from _pydev_imps._pydev_saved_modules import thread, threading
  File "/home/ryan/.eclipse/org.eclipse.platform_4.21.0_1473617060_linux_gtk_x86_64/plugins/org.python.pydev.core_9.1.0.202110031145/pysrc/_pydev_imps/_pydev_saved_modules.py", line 97, in <module>
    import thread;    verify_shadowed.check(thread, ['start_new_thread', 'start_new', 'allocate_lock'])
  File "/home/ryan/.eclipse/org.eclipse.platform_4.21.0_1473617060_linux_gtk_x86_64/plugins/org.python.pydev.core_9.1.0.202110031145/pysrc/_pydev_imps/_pydev_saved_modules.py", line 77, in check
    raise DebuggerInitializationError(msg)
_pydev_imps._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.

i.e.: the module "thread" could not be imported because it is shadowed by:
b
Please rename this file/folder so that the original module from the standard library can be imported.
```
So, it doesn't look like there's much we can do on the Ghidra end of things right now, other than document that the latest version of PyDev we support is 8.3.0.

**Comment by ryanmkurtz** [comment]
Thanks to @zZeck's efforts, this will be fixed in a future version of PyDev (likely the one after 9.1.0).  In the meantime, you can [manually implement the change they did in their PR](https://github.com/fabioz/Pydev/pull/354/files) in your PyDev's `plugins/org.python.pydev.core/pysrc/_pydev_imps/_pydev_saved_modules.py` file.
